[2019-04-12 14:42:55 -0400] [3755] [INFO] Starting gunicorn 19.9.0
[2019-04-12 14:42:55 -0400] [3755] [INFO] Listening at: http://0.0.0.0:5000 (3755)
[2019-04-12 14:42:55 -0400] [3755] [INFO] Using worker: sync
[2019-04-12 14:42:55 -0400] [3758] [INFO] Booting worker with pid: 3758
[2019-04-12 14:42:56 -0400] [3758] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/matthewbrown/Documents/Programming/Python/django-rest-framework-musicbrainz-api/django-rest-framework-api/django-rest-framework-api/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'django-rest-framework-api.settings.test'
[2019-04-12 14:42:56 -0400] [3758] [INFO] Worker exiting (pid: 3758)
[2019-04-12 14:42:56 -0400] [3755] [INFO] Shutting down: Master
[2019-04-12 14:42:56 -0400] [3755] [INFO] Reason: Worker failed to boot.
[2019-04-12 15:06:38 -0400] [4071] [INFO] Starting gunicorn 19.9.0
[2019-04-12 15:06:38 -0400] [4071] [INFO] Listening at: http://0.0.0.0:5000 (4071)
[2019-04-12 15:06:38 -0400] [4071] [INFO] Using worker: sync
[2019-04-12 15:06:38 -0400] [4075] [INFO] Booting worker with pid: 4075
[2019-04-12 15:06:38 -0400] [4075] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/matthewbrown/Documents/Programming/Python/django-rest-framework-musicbrainz-api/django-rest-framework-api/django-rest-framework-api/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/matthewbrown/.virtualenvs/ng_django/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'django-rest-framework-api.settings.test'
[2019-04-12 15:06:38 -0400] [4075] [INFO] Worker exiting (pid: 4075)
[2019-04-12 15:06:39 -0400] [4071] [INFO] Shutting down: Master
[2019-04-12 15:06:39 -0400] [4071] [INFO] Reason: Worker failed to boot.
[2019-04-12 15:07:00 -0400] [4119] [INFO] Starting gunicorn 19.9.0
[2019-04-12 15:07:00 -0400] [4119] [INFO] Listening at: http://0.0.0.0:5000 (4119)
[2019-04-12 15:07:00 -0400] [4119] [INFO] Using worker: sync
[2019-04-12 15:07:00 -0400] [4122] [INFO] Booting worker with pid: 4122
[2019-04-12 15:09:37 -0400] [4119] [INFO] Handling signal: int
[2019-04-12 19:09:37 +0000] [4122] [INFO] Worker exiting (pid: 4122)
[2019-04-12 15:09:37 -0400] [4119] [INFO] Shutting down: Master
